import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Providers from './redux/Providers'
import ThemeProviders from './ThemeProviders'
import Navbar from './components/Navbar'

const poppins = Poppins({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <Providers>
          <ThemeProviders>
            {children}
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  )
}
